/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as ClienteIndexRouteImport } from './routes/cliente/index'
import { Route as ClientePortalRouteImport } from './routes/cliente/_portal'
import { Route as ClientePortalSecaoRouteImport } from './routes/cliente/_portal/$secao'
import { Route as ClientePortalAgendaRouteImport } from './routes/cliente/_portal/agenda'
import { Route as ClientePortalAprovacoesRouteImport } from './routes/cliente/_portal/aprovacoes'
import { Route as ClientePortalArquivosRouteImport } from './routes/cliente/_portal/arquivos'
import { Route as ClientePortalInicioRouteImport } from './routes/cliente/_portal/inicio'
import { Route as ClientePortalMensagensRouteImport } from './routes/cliente/_portal/mensagens'
import { Route as ClientePortalAgenciaIndexRouteImport } from './routes/cliente/_portal/agencia.index'
import { Route as ClientePortalAgenciaSecaoRouteImport } from './routes/cliente/_portal/agencia.$secao'
import { Route as ClientePortalAgenciaAgendaRouteImport } from './routes/cliente/_portal/agencia.agenda'
import { Route as ClientePortalAgenciaArquivosRouteImport } from './routes/cliente/_portal/agencia.arquivos'
import { Route as ClientePortalAgenciaAutomacaoRouteImport } from './routes/cliente/_portal/agencia.automacao'
import { Route as ClientePortalAgenciaInboxRouteImport } from './routes/cliente/_portal/agencia.inbox'
import { Route as ClientePortalConteudoIndexRouteImport } from './routes/cliente/_portal/conteudo.index'
import { Route as ClientePortalConteudoIdRouteImport } from './routes/cliente/_portal/conteudo.$id'
import { Route as ClientePortalAgenciaClientesIndexRouteImport } from './routes/cliente/_portal/agencia.clientes.index'
import { Route as ClientePortalAgenciaClientesIdRouteImport } from './routes/cliente/_portal/agencia.clientes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePortalRoute = ClientePortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePortalSecaoRoute = ClientePortalSecaoRouteImport.update({
  id: '/$secao',
  path: '/$secao',
  getParentRoute: () => ClientePortalRoute,
} as any)
const ClientePortalAgendaRoute = ClientePortalAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ClientePortalRoute,
} as any)
const ClientePortalAprovacoesRoute = ClientePortalAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => ClientePortalRoute,
} as any)
const ClientePortalArquivosRoute = ClientePortalArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => ClientePortalRoute,
} as any)
const ClientePortalInicioRoute = ClientePortalInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => ClientePortalRoute,
} as any)
const ClientePortalMensagensRoute = ClientePortalMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => ClientePortalRoute,
} as any)
const ClientePortalAgenciaIndexRoute =
  ClientePortalAgenciaIndexRouteImport.update({
    id: '/agencia/',
    path: '/agencia/',
    getParentRoute: () => ClientePortalRoute,
  } as any)
const ClientePortalAgenciaSecaoRoute =
  ClientePortalAgenciaSecaoRouteImport.update({
    id: '/agencia/$secao',
    path: '/agencia/$secao',
    getParentRoute: () => ClientePortalRoute,
  } as any)
const ClientePortalAgenciaAgendaRoute =
  ClientePortalAgenciaAgendaRouteImport.update({
    id: '/agencia/agenda',
    path: '/agencia/agenda',
    getParentRoute: () => ClientePortalRoute,
  } as any)
const ClientePortalAgenciaArquivosRoute =
  ClientePortalAgenciaArquivosRouteImport.update({
    id: '/agencia/arquivos',
    path: '/agencia/arquivos',
    getParentRoute: () => ClientePortalRoute,
  } as any)
const ClientePortalAgenciaAutomacaoRoute =
  ClientePortalAgenciaAutomacaoRouteImport.update({
    id: '/agencia/automacao',
    path: '/agencia/automacao',
    getParentRoute: () => ClientePortalRoute,
  } as any)
const ClientePortalAgenciaInboxRoute =
  ClientePortalAgenciaInboxRouteImport.update({
    id: '/agencia/inbox',
    path: '/agencia/inbox',
    getParentRoute: () => ClientePortalRoute,
  } as any)
const ClientePortalConteudoIndexRoute =
  ClientePortalConteudoIndexRouteImport.update({
    id: '/conteudo/',
    path: '/conteudo/',
    getParentRoute: () => ClientePortalRoute,
  } as any)
const ClientePortalConteudoIdRoute = ClientePortalConteudoIdRouteImport.update({
  id: '/conteudo/$id',
  path: '/conteudo/$id',
  getParentRoute: () => ClientePortalRoute,
} as any)
const ClientePortalAgenciaClientesIndexRoute =
  ClientePortalAgenciaClientesIndexRouteImport.update({
    id: '/agencia/clientes/',
    path: '/agencia/clientes/',
    getParentRoute: () => ClientePortalRoute,
  } as any)
const ClientePortalAgenciaClientesIdRoute =
  ClientePortalAgenciaClientesIdRouteImport.update({
    id: '/agencia/clientes/$id',
    path: '/agencia/clientes/$id',
    getParentRoute: () => ClientePortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/cliente/': typeof ClienteIndexRoute
  '/cliente/$secao': typeof ClientePortalSecaoRoute
  '/cliente/agenda': typeof ClientePortalAgendaRoute
  '/cliente/aprovacoes': typeof ClientePortalAprovacoesRoute
  '/cliente/arquivos': typeof ClientePortalArquivosRoute
  '/cliente/inicio': typeof ClientePortalInicioRoute
  '/cliente/mensagens': typeof ClientePortalMensagensRoute
  '/cliente/agencia/$secao': typeof ClientePortalAgenciaSecaoRoute
  '/cliente/agencia/agenda': typeof ClientePortalAgenciaAgendaRoute
  '/cliente/agencia/arquivos': typeof ClientePortalAgenciaArquivosRoute
  '/cliente/agencia/automacao': typeof ClientePortalAgenciaAutomacaoRoute
  '/cliente/agencia/inbox': typeof ClientePortalAgenciaInboxRoute
  '/cliente/conteudo/$id': typeof ClientePortalConteudoIdRoute
  '/cliente/agencia/': typeof ClientePortalAgenciaIndexRoute
  '/cliente/conteudo/': typeof ClientePortalConteudoIndexRoute
  '/cliente/agencia/clientes/$id': typeof ClientePortalAgenciaClientesIdRoute
  '/cliente/agencia/clientes/': typeof ClientePortalAgenciaClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteIndexRoute
  '/cliente/$secao': typeof ClientePortalSecaoRoute
  '/cliente/agenda': typeof ClientePortalAgendaRoute
  '/cliente/aprovacoes': typeof ClientePortalAprovacoesRoute
  '/cliente/arquivos': typeof ClientePortalArquivosRoute
  '/cliente/inicio': typeof ClientePortalInicioRoute
  '/cliente/mensagens': typeof ClientePortalMensagensRoute
  '/cliente/agencia/$secao': typeof ClientePortalAgenciaSecaoRoute
  '/cliente/agencia/agenda': typeof ClientePortalAgenciaAgendaRoute
  '/cliente/agencia/arquivos': typeof ClientePortalAgenciaArquivosRoute
  '/cliente/agencia/automacao': typeof ClientePortalAgenciaAutomacaoRoute
  '/cliente/agencia/inbox': typeof ClientePortalAgenciaInboxRoute
  '/cliente/conteudo/$id': typeof ClientePortalConteudoIdRoute
  '/cliente/agencia': typeof ClientePortalAgenciaIndexRoute
  '/cliente/conteudo': typeof ClientePortalConteudoIndexRoute
  '/cliente/agencia/clientes/$id': typeof ClientePortalAgenciaClientesIdRoute
  '/cliente/agencia/clientes': typeof ClientePortalAgenciaClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/cliente/_portal': typeof ClientePortalRouteWithChildren
  '/cliente/': typeof ClienteIndexRoute
  '/cliente/_portal/$secao': typeof ClientePortalSecaoRoute
  '/cliente/_portal/agenda': typeof ClientePortalAgendaRoute
  '/cliente/_portal/aprovacoes': typeof ClientePortalAprovacoesRoute
  '/cliente/_portal/arquivos': typeof ClientePortalArquivosRoute
  '/cliente/_portal/inicio': typeof ClientePortalInicioRoute
  '/cliente/_portal/mensagens': typeof ClientePortalMensagensRoute
  '/cliente/_portal/agencia/$secao': typeof ClientePortalAgenciaSecaoRoute
  '/cliente/_portal/agencia/agenda': typeof ClientePortalAgenciaAgendaRoute
  '/cliente/_portal/agencia/arquivos': typeof ClientePortalAgenciaArquivosRoute
  '/cliente/_portal/agencia/automacao': typeof ClientePortalAgenciaAutomacaoRoute
  '/cliente/_portal/agencia/inbox': typeof ClientePortalAgenciaInboxRoute
  '/cliente/_portal/conteudo/$id': typeof ClientePortalConteudoIdRoute
  '/cliente/_portal/agencia/': typeof ClientePortalAgenciaIndexRoute
  '/cliente/_portal/conteudo/': typeof ClientePortalConteudoIndexRoute
  '/cliente/_portal/agencia/clientes/$id': typeof ClientePortalAgenciaClientesIdRoute
  '/cliente/_portal/agencia/clientes/': typeof ClientePortalAgenciaClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cliente'
    | '/cliente/'
    | '/cliente/$secao'
    | '/cliente/agenda'
    | '/cliente/aprovacoes'
    | '/cliente/arquivos'
    | '/cliente/inicio'
    | '/cliente/mensagens'
    | '/cliente/agencia/$secao'
    | '/cliente/agencia/agenda'
    | '/cliente/agencia/arquivos'
    | '/cliente/agencia/automacao'
    | '/cliente/agencia/inbox'
    | '/cliente/conteudo/$id'
    | '/cliente/agencia/'
    | '/cliente/conteudo/'
    | '/cliente/agencia/clientes/$id'
    | '/cliente/agencia/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cliente'
    | '/cliente/$secao'
    | '/cliente/agenda'
    | '/cliente/aprovacoes'
    | '/cliente/arquivos'
    | '/cliente/inicio'
    | '/cliente/mensagens'
    | '/cliente/agencia/$secao'
    | '/cliente/agencia/agenda'
    | '/cliente/agencia/arquivos'
    | '/cliente/agencia/automacao'
    | '/cliente/agencia/inbox'
    | '/cliente/conteudo/$id'
    | '/cliente/agencia'
    | '/cliente/conteudo'
    | '/cliente/agencia/clientes/$id'
    | '/cliente/agencia/clientes'
  id:
    | '__root__'
    | '/'
    | '/cliente'
    | '/cliente/_portal'
    | '/cliente/'
    | '/cliente/_portal/$secao'
    | '/cliente/_portal/agenda'
    | '/cliente/_portal/aprovacoes'
    | '/cliente/_portal/arquivos'
    | '/cliente/_portal/inicio'
    | '/cliente/_portal/mensagens'
    | '/cliente/_portal/agencia/$secao'
    | '/cliente/_portal/agencia/agenda'
    | '/cliente/_portal/agencia/arquivos'
    | '/cliente/_portal/agencia/automacao'
    | '/cliente/_portal/agencia/inbox'
    | '/cliente/_portal/conteudo/$id'
    | '/cliente/_portal/agencia/'
    | '/cliente/_portal/conteudo/'
    | '/cliente/_portal/agencia/clientes/$id'
    | '/cliente/_portal/agencia/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClienteRoute: typeof ClienteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/_portal': {
      id: '/cliente/_portal'
      path: ''
      fullPath: '/cliente'
      preLoaderRoute: typeof ClientePortalRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/_portal/$secao': {
      id: '/cliente/_portal/$secao'
      path: '/$secao'
      fullPath: '/cliente/$secao'
      preLoaderRoute: typeof ClientePortalSecaoRouteImport
      parentRoute: typeof ClientePortalRoute
    }
    '/cliente/_portal/agenda': {
      id: '/cliente/_portal/agenda'
      path: '/agenda'
      fullPath: '/cliente/agenda'
      preLoaderRoute: typeof ClientePortalAgendaRouteImport
      parentRoute: typeof ClientePortalRoute
    }
    '/cliente/_portal/aprovacoes': {
      id: '/cliente/_portal/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/cliente/aprovacoes'
      preLoaderRoute: typeof ClientePortalAprovacoesRouteImport
      parentRoute: typeof ClientePortalRoute
    }
    '/cliente/_portal/arquivos': {
      id: '/cliente/_portal/arquivos'
      path: '/arquivos'
      fullPath: '/cliente/arquivos'
      preLoaderRoute: typeof ClientePortalArquivosRouteImport
      parentRoute: typeof ClientePortalRoute
    }
    '/cliente/_portal/inicio': {
      id: '/cliente/_portal/inicio'
      path: '/inicio'
      fullPath: '/cliente/inicio'
      preLoaderRoute: typeof ClientePortalInicioRouteImport
      parentRoute: typeof ClientePortalRoute
    }
    '/cliente/_portal/mensagens': {
      id: '/cliente/_portal/mensagens'
      path: '/mensagens'
      fullPath: '/cliente/mensagens'
      preLoaderRoute: typeof ClientePortalMensagensRouteImport
      parentRoute: typeof ClientePortalRoute
    }
    '/cliente/_portal/agencia/': {
      id: '/cliente/_portal/agencia/'
      path: '/agencia'
      fullPath: '/cliente/agencia/'
      preLoaderRoute: typeof ClientePortalAgenciaIndexRouteImport
      parentRoute: typeof ClientePortalRoute
    }
    '/cliente/_portal/agencia/$secao': {
      id: '/cliente/_portal/agencia/$secao'
      path: '/agencia/$secao'
      fullPath: '/cliente/agencia/$secao'
      preLoaderRoute: typeof ClientePortalAgenciaSecaoRouteImport
      parentRoute: typeof ClientePortalRoute
    }
    '/cliente/_portal/agencia/agenda': {
      id: '/cliente/_portal/agencia/agenda'
      path: '/agencia/agenda'
      fullPath: '/cliente/agencia/agenda'
      preLoaderRoute: typeof ClientePortalAgenciaAgendaRouteImport
      parentRoute: typeof ClientePortalRoute
    }
    '/cliente/_portal/agencia/arquivos': {
      id: '/cliente/_portal/agencia/arquivos'
      path: '/agencia/arquivos'
      fullPath: '/cliente/agencia/arquivos'
      preLoaderRoute: typeof ClientePortalAgenciaArquivosRouteImport
      parentRoute: typeof ClientePortalRoute
    }
    '/cliente/_portal/agencia/automacao': {
      id: '/cliente/_portal/agencia/automacao'
      path: '/agencia/automacao'
      fullPath: '/cliente/agencia/automacao'
      preLoaderRoute: typeof ClientePortalAgenciaAutomacaoRouteImport
      parentRoute: typeof ClientePortalRoute
    }
    '/cliente/_portal/agencia/inbox': {
      id: '/cliente/_portal/agencia/inbox'
      path: '/agencia/inbox'
      fullPath: '/cliente/agencia/inbox'
      preLoaderRoute: typeof ClientePortalAgenciaInboxRouteImport
      parentRoute: typeof ClientePortalRoute
    }
    '/cliente/_portal/conteudo/': {
      id: '/cliente/_portal/conteudo/'
      path: '/conteudo'
      fullPath: '/cliente/conteudo/'
      preLoaderRoute: typeof ClientePortalConteudoIndexRouteImport
      parentRoute: typeof ClientePortalRoute
    }
    '/cliente/_portal/conteudo/$id': {
      id: '/cliente/_portal/conteudo/$id'
      path: '/conteudo/$id'
      fullPath: '/cliente/conteudo/$id'
      preLoaderRoute: typeof ClientePortalConteudoIdRouteImport
      parentRoute: typeof ClientePortalRoute
    }
    '/cliente/_portal/agencia/clientes/': {
      id: '/cliente/_portal/agencia/clientes/'
      path: '/agencia/clientes'
      fullPath: '/cliente/agencia/clientes/'
      preLoaderRoute: typeof ClientePortalAgenciaClientesIndexRouteImport
      parentRoute: typeof ClientePortalRoute
    }
    '/cliente/_portal/agencia/clientes/$id': {
      id: '/cliente/_portal/agencia/clientes/$id'
      path: '/agencia/clientes/$id'
      fullPath: '/cliente/agencia/clientes/$id'
      preLoaderRoute: typeof ClientePortalAgenciaClientesIdRouteImport
      parentRoute: typeof ClientePortalRoute
    }
  }
}

interface ClientePortalRouteChildren {
  ClientePortalSecaoRoute: typeof ClientePortalSecaoRoute
  ClientePortalAgendaRoute: typeof ClientePortalAgendaRoute
  ClientePortalAprovacoesRoute: typeof ClientePortalAprovacoesRoute
  ClientePortalArquivosRoute: typeof ClientePortalArquivosRoute
  ClientePortalInicioRoute: typeof ClientePortalInicioRoute
  ClientePortalMensagensRoute: typeof ClientePortalMensagensRoute
  ClientePortalAgenciaSecaoRoute: typeof ClientePortalAgenciaSecaoRoute
  ClientePortalAgenciaAgendaRoute: typeof ClientePortalAgenciaAgendaRoute
  ClientePortalAgenciaArquivosRoute: typeof ClientePortalAgenciaArquivosRoute
  ClientePortalAgenciaAutomacaoRoute: typeof ClientePortalAgenciaAutomacaoRoute
  ClientePortalAgenciaInboxRoute: typeof ClientePortalAgenciaInboxRoute
  ClientePortalConteudoIdRoute: typeof ClientePortalConteudoIdRoute
  ClientePortalAgenciaIndexRoute: typeof ClientePortalAgenciaIndexRoute
  ClientePortalConteudoIndexRoute: typeof ClientePortalConteudoIndexRoute
  ClientePortalAgenciaClientesIdRoute: typeof ClientePortalAgenciaClientesIdRoute
  ClientePortalAgenciaClientesIndexRoute: typeof ClientePortalAgenciaClientesIndexRoute
}

const ClientePortalRouteChildren: ClientePortalRouteChildren = {
  ClientePortalSecaoRoute: ClientePortalSecaoRoute,
  ClientePortalAgendaRoute: ClientePortalAgendaRoute,
  ClientePortalAprovacoesRoute: ClientePortalAprovacoesRoute,
  ClientePortalArquivosRoute: ClientePortalArquivosRoute,
  ClientePortalInicioRoute: ClientePortalInicioRoute,
  ClientePortalMensagensRoute: ClientePortalMensagensRoute,
  ClientePortalAgenciaSecaoRoute: ClientePortalAgenciaSecaoRoute,
  ClientePortalAgenciaAgendaRoute: ClientePortalAgenciaAgendaRoute,
  ClientePortalAgenciaArquivosRoute: ClientePortalAgenciaArquivosRoute,
  ClientePortalAgenciaAutomacaoRoute: ClientePortalAgenciaAutomacaoRoute,
  ClientePortalAgenciaInboxRoute: ClientePortalAgenciaInboxRoute,
  ClientePortalConteudoIdRoute: ClientePortalConteudoIdRoute,
  ClientePortalAgenciaIndexRoute: ClientePortalAgenciaIndexRoute,
  ClientePortalConteudoIndexRoute: ClientePortalConteudoIndexRoute,
  ClientePortalAgenciaClientesIdRoute: ClientePortalAgenciaClientesIdRoute,
  ClientePortalAgenciaClientesIndexRoute:
    ClientePortalAgenciaClientesIndexRoute,
}

const ClientePortalRouteWithChildren = ClientePortalRoute._addFileChildren(
  ClientePortalRouteChildren,
)

interface ClienteRouteChildren {
  ClientePortalRoute: typeof ClientePortalRouteWithChildren
  ClienteIndexRoute: typeof ClienteIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClientePortalRoute: ClientePortalRouteWithChildren,
  ClienteIndexRoute: ClienteIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClienteRoute: ClienteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
